// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA25vqQPqyr8gZJ83_l3GIDJvW_9s69NoY',
    appId: '1:945793861093:web:b6811a8d3b33a0d25f5b0c',
    messagingSenderId: '945793861093',
    projectId: 'expensetracker-87061',
    authDomain: 'expensetracker-87061.firebaseapp.com',
    storageBucket: 'expensetracker-87061.appspot.com',
    measurementId: 'G-W0JEFDB2QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFIp46k8amxUa6SaMfqg5U231ZMtGw0dw',
    appId: '1:945793861093:android:6895e2280ba90bc75f5b0c',
    messagingSenderId: '945793861093',
    projectId: 'expensetracker-87061',
    storageBucket: 'expensetracker-87061.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNZwQCCyNP-lap0WSDPUNqMQrgKu6Ic_I',
    appId: '1:945793861093:ios:8ee2a8311f88fabd5f5b0c',
    messagingSenderId: '945793861093',
    projectId: 'expensetracker-87061',
    storageBucket: 'expensetracker-87061.appspot.com',
    iosClientId: '945793861093-sur7lltliq0uurreb0sst6qd934vnl7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNZwQCCyNP-lap0WSDPUNqMQrgKu6Ic_I',
    appId: '1:945793861093:ios:a2b501673e8e98415f5b0c',
    messagingSenderId: '945793861093',
    projectId: 'expensetracker-87061',
    storageBucket: 'expensetracker-87061.appspot.com',
    iosClientId: '945793861093-ff4og68ikeuc16bbat9p6kjh1go3cmgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensetracker.RunnerTests',
  );
}
